apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: articles
  name: articles
  namespace: ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles 
  strategy: {}
  template:
    metadata:
      labels:
        app: articles
    spec:
      containers:
      - image: gonzaloacosta/python-fastapi-articles:0.0.8
        name: articles
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m" 
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
        imagePullPolicy: Always
