apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: default
  name: auth
  namespace: ingest
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: auth 
          servicePort: 8080
        path: /auth
        pathType: Prefix
