apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
  namespace: ingest
spec:
  ports:
  - port: 8080 
    protocol: TCP
    targetPort: 80
  selector:
    app: auth
  type: ClusterIP
